version: '3'

services:
  autopyara:
    stdin_open: true
    tty: true
    build: .
    command: bash
    container_name: autopyara_docker
    deploy:
      resources:
        limits:
          cpus: '20'  
    volumes:
      - /home/mabon/research/Autoyara/AutoPYara/AutoPYara:/usr/src/app/
      - ./intermediate:/usr/src/app/intermediate/
      - ../jars:/usr/src/app/jars/
      - /home/mabon/research/Autoyara/YaraResults:/usr/src/app/YaraResults
      - /mnt/data_disk1/mabon/:/usr/src/app/HDDdata
