version: '3'

services:
  autopyara:
    stdin_open: true
    tty: true
    build: .
    command: bash
    cpuset: "64"  # Limits to 10 cores
    container_name: autopyara_docker
    volumes:
      - /home/mabon/research/Autoyara/AutoPYara/mlsec-prototype:/usr/src/app/
      - ./intermediate:/usr/src/app/intermediate/
      - ./output:/usr/src/app/output/
      - ../jars:/usr/src/app/jars/
      - /home/malware/datasets/samples/malware/Windows/Honeypots:/usr/src/app/Honeypots
      - /mnt/data_disk1/mabon/processed_data/BB/files:/usr/src/app/ssdeepdata
      - /mnt/data_disk1/mabon/datacopy:/usr/src/app/datacopy
