python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th50.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Max/Th50rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Max/sdhashRTBF_TH50.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th60.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Max/Th60rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Max/sdhashRTBF_TH60.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th70.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Max/Th70rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Max/sdhashRTBF_TH70.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th80.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Max/Th80rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Max/sdhashRTBF_TH80.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th90.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Max/Th90rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Max/sdhashRTBF_TH90.csv



python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th50.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/AVG/Th50rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/AVG/sdhashRTBF_TH50.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th60.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/AVG/Th60rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/AVG/sdhashRTBF_TH60.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th70.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/AVG/Th70rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/AVG/sdhashRTBF_TH70.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th80.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/AVG/Th80rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/AVG/sdhashRTBF_TH80.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th90.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/AVG/Th90rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/AVG/sdhashRTBF_TH90.csv

python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th50.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Random/Th50rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Random/sdhashRTBF_TH50.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th60.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Random/Th60rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Random/sdhashRTBF_TH60.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th70.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Random/Th70rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Random/sdhashRTBF_TH70.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th80.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Random/Th80rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Random/sdhashRTBF_TH80.csv
python yaraCrossRuleEvalGoodware.py --csv-file /usr/src/app/YaraResults/clusterCSV/sdhash/Th90.csv --datapath /usr/src/app/YaraResults/masterCSV/datasetGoodwarePE.csv --rPaths /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/Heuristic/VTHeu/Random/Th90rules/merged_group_1.yar --opfile /usr/src/app/YaraResults/ruleEval/retrainedBloomFilters/sdhash/AutoPYara/GoodwareEval/Heuristic/VTHeu/Random/sdhashRTBF_TH90.csv



